name: transformer
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - matplotlib
  - numpy
  - tqdm
  - requests
  - pip
  - pip:
    - datasets
    - tokenizers
    - wandb